repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: sort-simple-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-byte-order-marker
  - id: check-merge-conflict
- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
  - id: black
- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    args:
    - --extend-ignore=E203
    - --max-complexity=20
    - --max-line-length=88
    - --show-source
    - --statistics
