# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: "Format, Lint, and Test"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11.5
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.5"
    - name: Install dependencies
      run: |
        /usr/bin/python -m pip install --upgrade pip
        /usr/bin/pip install -r requirements.txt
        /usr/bin/pip install -e helpers
    - name: Run Pre-Commit Hooks
      run: pre-commit run --all-files
    - name: Run tests
      run: ./run_tests.sh
